/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include "uart.h"
#include "gpio.h"


#define     USART2_IRQn           38U
#define     NVIC_ISER_INDEX      (USART2_IRQn / 32U)
#define     NVIC_ISER_BIT        (USART2_IRQn % 32U)
#define     NVIC_ISER_MASK       (1U << NVIC_ISER_BIT)

#define     COMMAND_BUFFER_SIZE  64U

static void process_command(const char *command);
static char command_buffer[COMMAND_BUFFER_SIZE];
static uint8_t command_index = 0;

static void process_command(const char *command)
{
	if (command[0] == '\0')
	{
		return;
	}
	if (strcmp(command, "led on") == 0)
	{
		gpio_led_on();
		printf("\r\nLED ON\r\n");
	}
	else if (strcmp(command, "led off") == 0)
	{
		gpio_led_off();
		printf("\r\nLED OFF\r\n");
	}
	else if (strcmp(command, "led toggle") == 0)
	{
		gpio_led_toggle();
		printf("\r\nLED TOGGLED\r\n");
	}
	else if (strcmp(command, "status") == 0)
	{
		if (gpio_led_get_state())
		{
			printf("\r\nLED: ON\r\n");
		}
		else
		{
			printf("\r\n LED: OFF\r\n");
		}
	}
	else if (strcmp(command, "help") == 0)
	{
		printf("\r\nCommands:\r\n");
		printf("  led on\r\n");
		printf("  led off\r\n");
		printf("  led toggle\r\n");
		printf("  status\r\n");
		printf("  echo <text>\r\n");
		printf("  help\r\n");
	}
	else if (command[0] == 'e' &&
			 command[1] == 'c' &&
			 command[2] == 'h' &&
			 command[3] == 'o' &&
			 command[4] == ' ')
	{
		printf("\r\nECHO: %s\r\n", &command[5]);
	}
	else
	{
		printf("\r\nUnknown command: %s\r\n", command);
	}
}

int main(void)
{
	uint8_t data;

	gpio_init();
	uart2_init();

	NVIC_ISER1 = NVIC_ISER_MASK;

	while(1)
	{
		if(uart2_read_nonblocking(&data))
		{
			if ((data != '\r') && (data != '\n'))
			{
				if (command_index < (COMMAND_BUFFER_SIZE - 1U))
				{
					command_buffer[command_index] = (char)data;
					command_index++;
				}
			}
			else
			{
				command_buffer[command_index] = '\0';

				process_command(command_buffer);

				command_index = 0;
			}
		}
	}
}
