/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx_reg.h"
#include "gpio.h"
#include "adc.h"
#include "uart.h"
#include "systick.h"


int main(void)
{

	/* Initialize GPIO related stuffs */
	gpio_init();

	/* Initialize ADC related stuffs */
	adc_init();

	/* Initialize UART Transfer */
	uart_tx_init();

	adc_irq_ready = false;

	/* ADC1: enable end-of-conversion interrupt */
	ADC1_CR1 |= (1U << 5);

	/* NVIC: enable the ADC interrupt, IRQ number 18 */
	NVIC_ISER0 |= (1U << 18);

	/* Start one conversation */
	ADC1_CR2 |= (1U << 30);


   while(1)
   {

	   if(adc_irq_ready)
	   {
		  uint32_t sample = adc_irq_value;
		  adc_irq_ready = false;

		   printf("ADC interrupt result = %lu\r\n",
				  (unsigned long)sample);
	   }

	   /* Other application work can go here */
	}
}
