/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "uart.h"
#include "gpio.h"

int main(void)
{
	gpio_init();
	uart_rxtx_init();

	printf("UART2 interrupt driven LED Project started\r\n");

    while (1)
    {
    	uint32_t command = uart2_take_command();
    	if (command == '1')
    	{
    		led_on();
    		printf("LED ON\r\n");
    	}
    	else if (command == '0')
    	{
        	led_off();
        	printf("LED OFF\r\n");
    	}
    }
}
