/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "uart.h"
#include "gpio.h"
#include "exti.h"

int main(void)
{
    gpio_init();
    uart_tx_init();
    setvbuf(stdout, NULL, _IONBF, 0);
    exti_pc13_init();

    printf("NUCLEO-F446RE ready: press B1 (PC13).\r\n");

    while (1)
    {
        if (exti13_take_event())
        {
            gpio_toggle();
            printf("EXTI13 event: LD2 (PA5) toggled.\r\n");
        }
    }
}
