/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx_reg.h"
#include "gpio.h"
#include "adc.h"
#include "uart.h"
#include "systick.h"

volatile uint32_t adc_value = 0;

int main(void)
{

	/* Initialize GPIO related stuffs */
	gpio_init();

	/* Initialize ADC related stuffs */
	adc_init();

	/* Initialize UART Transfer */
	uart_tx_init();

	/* Initialize systick timer */
	systick_init_100ms();

   while(1)
   {

	   systick_wait_tick();

	   uint32_t sample;

	   if(adc_read(&sample))
	   {
		   adc_value = sample;

		   printf("ADC = %lu\r\n", (unsigned long)adc_value);
	   }
	   else
	   {
		   printf("ADC timeout\r\n");

		   /* Stop here so we can investigate.
		    * this version does not attempt recovery
		    */

		   while(1)
		   {
		   }

	   }
   }
}
