/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "tim2.h"
#include "gpio.h"

uint32_t timestamp = 0;

/* Set up: connect a jumper wire from PA5 to PA6 */
int main(void)
{

	gpio_init();
	tim2_init_output_compare();
	tim3_input_capture();

	while(1)
	{
		/* wait until input is captured */
		while(!(TIM3_SR & TIM3_SR_CC1IF)) {}

		/* Read captured  input */
		timestamp = TIM3_CCR1;

	}
}
