/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "uart.h"
#include "gpio.h"


#define     LED_PIN              (1U << 5)
#define     USART2_IRQn           38U
#define     NVIC_ISER_INDEX      (USART2_IRQn / 32U)
#define     NVIC_ISER_BIT        (USART2_IRQn % 32U)
#define     NVIC_ISER_MASK       (1U << NVIC_ISER_BIT)


char key;

int main(void)
{
	gpio_init();
	uart2_init();
	NVIC_ISER1 = NVIC_ISER_MASK;

	while(1)
	{
		if(rx_ready)
		{
			key = rx_data;
			rx_ready = 0;

			uart2_write(key);

			if (key == '1')
			{
				GPIOA_ODR |= LED_PIN;
			}
			else if (key == '0')
			{
				GPIOA_ODR &= ~LED_PIN;
			}

		}
	}
}
