/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx_reg.h"
#include "led.h"
#include "led_pattern.h"
#include "soft_timer.h"
#include "gpio.h"
#include "interrupt.h"


volatile uint8_t  button_event  = 0;
volatile uint32_t ms_count      = 0;

/*==================================================================
 * SysTick Interrupt Handler
 *
 *==================================================================*/

void SysTick_Handler(void)
{
	ms_count++;

	SoftTimer_TickAll();
}

/*==================================================================
 * Main Application
 *
 *==================================================================*/

int main(void)
{
	/* Hardware initialization */
    GPIO_Init();
    EXTI0_Init();

	/* SysTick: 1 ms tick */
	SYST_RVR = 16000 - 1;
	SYST_CVR = 0;
	SYST_CSR = (1U << 0) | (1U << 1) | (1U << 2);

	/* Start pattern timer */
	SoftTimer_Start(&timers[TIMER_PATTERN], 500, TIMER_PERIODIC);

	/* Initialize LED pattern */
	LEDPattern_Init();

	/*=================================
	 * Main Application Loop
	 *=================================*/

	while(1)
	{
		/* Execute current LED pattern */
		LEDPattern_Run();

		/* De-bounce timer expired */
		if(SoftTimer_Expired(&timers[TIMER_BUTTON_DEBOUNCE]))
		{
			button_event = 1;
		}

		/* Process button event */
		if (button_event)
		{
			button_event = 0;

			LEDPattern_Next();
		}

	}
}


