/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "uart.h"
#include "gpio.h"


#define     LED_PIN         (1U << 5)
char key;

int main(void)
{
	gpio_init();
	uart_rxtx_init();

    uart2_write('H');
    uart2_write('i');
    uart2_write('\r');
    uart2_write('\n');

	while(1)
	{
	   uart2_write(key);

       key = uart2_read();
       if (key == '1')
       {
		   GPIOA_ODR |= LED_PIN;
       }
       else
       {
		   GPIOA_ODR &= ~LED_PIN;
       }
	}
}
